[project]
name = "aes-web-scrape"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gspread>=6.1.4",
    "oauth2client>=4.1.3",
    "requests>=2.32.3",
]
